- name: Stop existing container (if running)
  shell: docker stop webapp || true

- name: Remove old container
  shell: docker rm webapp || true

- name: Run new container with the latest image
  shell: |
    docker run -d --name webapp \
    -p {{ host_port }}:{{ container_port }} \
    --restart always \
    "{{ docker_image }}:{{ docker_tag }}"
