- name: Pull the latest Docker image (only for remote servers)
  shell: docker pull {{ docker_image }}
  when: inventory_hostname != "localhost"

- name: Stop existing container
  shell: docker stop webapp || true

- name: Remove old container
  shell: docker rm webapp || true

- name: Start new container with updated image
  shell: |
    docker run -d --name webapp \
    -p {{ host_port }}:{{ container_port }} \
    --restart always \
    "{{ docker_image }}:{{ docker_tag }}"
