- name: Deploy Web App Locally
  hosts: all
  connection: local
  become: false
  vars:
    docker_image: "{{ docker_image }}"
    docker_tag: "{{ docker_tag }}"
    action: "{{ action }}"
    host_port: "{{ host_port }}"
    container_port: "{{ container_port }}"
    secret_key: ""
  roles:
    - webapp
